/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tbs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author patel
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */int a1=0,flg=0;
    public Loading() {
        initComponents();
        Timer timer =new Timer();
        TimerTask task = new TimerTask()
                {
                    public void run()
                {
                  a1++;  
                  p1.setValue(a1);
                }
                };
        timer.scheduleAtFixedRate(task,0,100);
    }
    String m,m1,u,d,alpha,a;
 public Loading(String par1,String par2,String par3,String par4,String par5,String par6) {
        initComponents();
        m=par1;
        m1=par2;
        u=par3;
        d=par4;
        alpha=par5;
        a=par6;
        Timer timer =new Timer();
        TimerTask task = new TimerTask()
                {
                    public void run()
                {
                  a1++;  
                  p1.setValue(a1);
                }
                };
        timer.scheduleAtFixedRate(task,0,100);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        p1.setBackground(new java.awt.Color(51, 51, 255));
        p1.setForeground(new java.awt.Color(0, 0, 255));
        p1.setName(""); // NOI18N
        p1.setStringPainted(true);
        p1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                p1StateChanged(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tbs/B_D-round-green-fghdot.png"))); // NOI18N
        jLabel1.setOpaque(true);

        l1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_p1StateChanged
        if(p1.getValue()==100)
        {
            System.out.println(flg+"");
            new TheaterOwner(a).setVisible(true);
            dispose();
        }
        if(p1.getValue()<=50)
        {
            l1.setText("Adding New Movie");
        }
        else if(p1.getValue()>50)
        {
            l1.setText("Creating new Timing Slot");
        }
    }//GEN-LAST:event_p1StateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       flg++;
       String ak;
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tbs?useSSL=false", "root", "1234");
            Statement stmt = con.createStatement();
            if(m1.equals("Add movie 1"))
            {
                ak="seat1";
            }
            else if(m1.equals("Add movie 2"))
            {
                ak="seat2";
            }
            else if(m1.equals("Add movie 3"))
            {
                ak="seat3";
            }
            else if(m1.equals("Add movie 4"))
            {
                ak="seat4";
            }
            else{
            String q="Select tbname from movietable where movie='"+m1+"';";
            ResultSet rs=stmt.executeQuery(q);
            ak=rs.getString(1);
            String qu="delete from movietable where tbname='"+m1+"';";
            stmt.execute(qu);
           }
             String qu2="drop table if exists "+ak+";";
            stmt.execute(qu2);
            String que = "Insert into movietable values('"+m+"','"+d+"','"+alpha+"','"+u+"','"+ak+"');";
            stmt.execute(que);
            String quer="Create table "+ak+"(seats char(2),ss11 char(1),ss12 char(1),ss13 char(1),ss14 char(1),ss21 char(1),ss22 char(1),ss23 char(1),ss24 char(1),ss31 char(1),ss32 char(1),ss33 char(1),ss34 char(1),ss41 char(1),ss42 char(1),ss43 char(1),ss44 char(1),ss51 char(1),ss52 char(1),ss53 char(1),ss54 char(1),ss61 char(1),ss62 char(1),ss63 char(1),ss64 char(1),ss71 char(1),ss72 char(1),ss73 char(1),ss74 char(1));";
            stmt.execute(quer);
            for(char i='a';i<='g';i++)
            {
                for(int j=1;j<=8;j++)
                {
                    String query="Insert into "+ak+" values('"+i+j+"','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n','n');";
                     stmt.execute(query);
                }
            }
       }
       catch(Exception e)
       {
           System.out.print(e.getMessage());
       }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JProgressBar p1;
    // End of variables declaration//GEN-END:variables
}
