/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tbs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.awt.Image;

/**
 *
 * @author Deep Rodge
 */
public class MovieSelect extends javax.swing.JFrame {

    /**
     * Creates new form MovieSelect
     */
    public MovieSelect() {
        initComponents();
    }
    String a;

    public MovieSelect(String par) {
        initComponents();
        a = par;

    }
    int f=0;
String d2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jop = new javax.swing.JOptionPane();
        jButton1 = new javax.swing.JButton();
        tb1 = new javax.swing.JToggleButton();
        tb2 = new javax.swing.JToggleButton();
        tb3 = new javax.swing.JToggleButton();
        tb4 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        j1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        j2 = new javax.swing.JList<>();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tb1);
        tb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tb1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tb1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tb1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(tb2);
        tb2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tb2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tb2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tb2ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(tb3);
        tb3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tb3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tb3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tb3ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(tb4);
        tb4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tb4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tb4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tb4ItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Shows Available:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Shows Today:");

        l7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        l7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        j1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        j1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        j1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                j1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(j1);

        j2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        j2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(j2);

        l1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 102, 102));

        l2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314)
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tb1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tb2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tb3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tb4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tb1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tb2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tb4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(104, 104, 104)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
long ad2;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        String mot="y";
        try {
        Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tbs?useSSL=false", "root", "1234");
            Statement stmt = con.createStatement();
            String qu = "Select * from movietable";
            ResultSet rs = stmt.executeQuery(qu);
            int size;
            rs.last();
            size = rs.getRow();
            if (size == 0) {
                mot = "n";
            }
        }
        catch (Exception e) {
                }
        if(mot.equals("n"))
        {
             JOptionPane.showMessageDialog(null,"New Here, Sorry no movie is available.\nPlease Be a theater owner to add movies");
             new Login().setVisible(true);
             dispose();
        }
        else{
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {
            public void run() {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                l2.setText(s.format(d));
            }
        };
        timer.scheduleAtFixedRate(task, 0, 100);

        l1.setText("" + java.time.LocalDate.now() + " " + java.time.DayOfWeek.from(java.time.LocalDate.now()));
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tbs?useSSL=false", "root", "1234");
            Statement stmt = con.createStatement();
            String qu = "Select movie,url from movietable";
            ResultSet rs = stmt.executeQuery(qu);
            int f = 0;
            while (rs.next()) {
                f++;
                String a2 = rs.getString(1);
                String b = rs.getString(2);
                if (f == 1) {
                    tb1.setText(a2);
                   ImageIcon icon = new ImageIcon(new ImageIcon(b).getImage().getScaledInstance(268, 268, Image.SCALE_DEFAULT));
                    tb1.setIcon(icon);
                }
                if (f == 2) {
                    tb2.setText(a2);
                    ImageIcon icon = new ImageIcon(new ImageIcon(b).getImage().getScaledInstance(268, 268, Image.SCALE_DEFAULT));
                    tb2.setIcon(icon);
                }
                if (f == 3) {
                    tb3.setText(a2);
                    ImageIcon icon = new ImageIcon(new ImageIcon(b).getImage().getScaledInstance(268, 268, Image.SCALE_DEFAULT));
                    tb3.setIcon(icon);
                }
                if (f == 4) {
                    tb4.setText(a2);
                    ImageIcon icon = new ImageIcon(new ImageIcon(b).getImage().getScaledInstance(268, 268, Image.SCALE_DEFAULT));
                    tb4.setIcon(icon);
                }
            }
        } catch (Exception e) {
                }
       }    }//GEN-LAST:event_formWindowActivated

    private void j1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_j1ValueChanged
        DefaultListModel ld = new DefaultListModel();
        String alpha;
        outer:
        {
            String ak;
            d2 = j1.getSelectedValue();
            switch (f) {
                case 1:
                    ak = tb1.getText();
                    break;
                case 2:
                    ak = tb2.getText();
                    break;
                case 3:
                    ak = tb3.getText();
                    break;
                case 4:
                    ak = tb4.getText();
                    break;
                default:
                    break outer;
            }
            try {
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tbs?useSSL=false", "root", "1234");
                Statement stmt = con.createStatement();
                String qu = "Select time from movietable where movie='" + ak + "';";
                ResultSet rs = stmt.executeQuery(qu);
                rs.next();
                alpha = rs.getString(1);
            } catch (Exception e) {
                System.out.print("1"+e);
                break outer;
            }
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("yyyyMMddHHmmss");
            String d1 = s.format(d);
            long ad = Long.parseLong(d1);

            String d3 = d2.substring(6, 10) + d2.substring(3, 5) + d2.substring(0, 2);
            long a1 = Long.parseLong(d3);
            int j, i = 130000;
            for (j = 0; j < 4; j++) {
                long a2 = a1 * 1000000 + i;
                 if (alpha.charAt(j) == '1') {
                    if (a2 > ad) {
                        int x = i % 1000000;
                        int y = (x / 10000)-12;
                        ld.addElement(y + ":00 pm");
                    }
                } else if (alpha.charAt(j) == '0') {

                }
                i += 30000;
            }
            j2.setModel(ld);
        }
    }//GEN-LAST:event_j1ValueChanged

    private void tb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tb1ItemStateChanged
       
        if (evt.getStateChange()==1)
        {
            f=1;
                        try {
                            DefaultListModel ld = new DefaultListModel();
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tbs?useSSL=false", "root", "1234");
                Statement stmt = con.createStatement();
                String qu = "Select date from movietable where movie='" + tb1.getText() + "';";
                String aa ;
                ResultSet rs = stmt.executeQuery(qu);
                rs.next();
                aa = rs.getString(1);
               
                String d21 = aa.substring(0, 4) + aa.substring(5, 7) + aa.substring(8, 10);
                ad2 = Long.parseLong(d21);
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("yyyyMMdd");
                String d1 = s.format(d);
                
                long ad1 = Long.parseLong(d1);
                long ad3=ad2+6;
                for (; ad1 <=ad3 ; ad1++) {
                    if (ad2 <= ad1) {
                        String dd=ad1+"";
                        dd= dd.substring(6, 8)+ "-"+ dd.substring(4, 6) + "-" +dd.substring(0, 4);
                        ld.addElement(dd);
                    }
                    
                 }
                j1.setModel(ld);
            } catch (Exception e) {
             System.out.print("2"+e);
            }
        }
        else 
        {
            f=0;
            j1.removeAll();
        }
    }//GEN-LAST:event_tb1ItemStateChanged

    private void tb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tb2ItemStateChanged
           if (evt.getStateChange()==1)
        {
            f=2;
                        try {
                            DefaultListModel ld = new DefaultListModel();
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tbs?useSSL=false", "root", "1234");
                Statement stmt = con.createStatement();
                String qu = "Select date from movietable where movie='" + tb2.getText() + "';";
                String aa ;
                ResultSet rs = stmt.executeQuery(qu);
                rs.next();
                aa = rs.getString(1);
               
                String d21 = aa.substring(0, 4) + aa.substring(5, 7) + aa.substring(8, 10);
                ad2 = Long.parseLong(d21);
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("yyyyMMdd");
                String d1 = s.format(d);
                
                long ad1 = Long.parseLong(d1);
                long ad3=ad2+6;
                for (; ad1 <=ad3 ; ad1++) {
                    if (ad2 <= ad1) {
                        String dd=ad1+"";
                        dd= dd.substring(6, 8)+ "-"+ dd.substring(4, 6) + "-" +dd.substring(0, 4);
                      
                        ld.addElement(dd);
                    }
                    
                 }
                j1.setModel(ld);
            } catch (Exception e) {
             System.out.print("3"+e);
            }
        }
        else 
        {
            f=0;
            j1.removeAll();
        }
    }//GEN-LAST:event_tb2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        outer:{
            if(j2.getSelectedIndex()==(-1))
       {
        JOptionPane.showMessageDialog(null,"Please Select Appropriately");
       }
       else
       {
           String t1=j2.getSelectedValue();
           int t;
           if(t1.equals("1:00 pm"))
           {
              t=1; 
           }
           else if(t1.equals("4:00 pm"))
           {
              t=2; 
           }
           else if (t1.equals("7:00 pm")) {
              t=3;
           }
           else if(t1.equals("10:00 pm"))
           {
              t=4; 
           }
           else
               break outer;
        String d3 = d2.substring(6, 10) + d2.substring(3, 5) + d2.substring(0, 2);
        long ad=Long.parseLong(d3);
        long dd=ad-ad2+1;
        new TheaterSeats(f,dd,a,t,ad).setVisible(true);
        dispose();
       }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tb3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tb3ItemStateChanged
        if (evt.getStateChange()==1)
        {
            f=3;
                        try {
                            DefaultListModel ld = new DefaultListModel();
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tbs?useSSL=false", "root", "1234");
                Statement stmt = con.createStatement();
                String qu = "Select date from movietable where movie='" + tb3.getText() + "';";
                String aa ;
                ResultSet rs = stmt.executeQuery(qu);
                rs.next();
                aa = rs.getString(1);
               
                String d21 = aa.substring(0, 4) + aa.substring(5, 7) + aa.substring(8, 10);
                ad2 = Long.parseLong(d21);
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("yyyyMMdd");
                String d1 = s.format(d);
                
                long ad1 = Long.parseLong(d1);
                long ad3=ad2+6;
                for (; ad1 <=ad3 ; ad1++) {
                    if (ad2 <= ad1) {
                        String dd=ad1+"";
                        dd= dd.substring(6, 8)+ "-"+ dd.substring(4, 6) + "-" +dd.substring(0, 4);
                        
                        ld.addElement(dd);
                    }
                    
                 }
                j1.setModel(ld);
            } catch (Exception e) {
             System.out.print("5"+e);
            }
        }
        else 
        {
            f=0;
            j1.removeAll();
        }
    }//GEN-LAST:event_tb3ItemStateChanged

    private void tb4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tb4ItemStateChanged
         if (evt.getStateChange()==1)
        {
            f=4;
                        try {
                            DefaultListModel ld = new DefaultListModel();
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/tbs?useSSL=false", "root", "1234");
                Statement stmt = con.createStatement();
                String qu = "Select date from movietable where movie='" + tb4.getText() + "';";
                String aa ;
                ResultSet rs = stmt.executeQuery(qu);
                rs.next();
                aa = rs.getString(1);
               
                String d21 = aa.substring(0, 4) + aa.substring(5, 7) + aa.substring(8, 10);
                ad2 = Long.parseLong(d21);
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("yyyyMMdd");
                String d1 = s.format(d);
                
                long ad1 = Long.parseLong(d1);
                long ad3=ad2+6;
                for (; ad1 <=ad3 ; ad1++) {
                    if (ad2 <= ad1) {
                        String dd=ad1+"";
                        dd= dd.substring(6, 8)+ "-"+ dd.substring(4, 6) + "-" +dd.substring(0, 4);
                        
                        ld.addElement(dd);
                    }
                    
                 }
                j1.setModel(ld);
            } catch (Exception e) {
             System.out.print("6"+e);
            }
        }
        else 
        {
            f=0;
            j1.removeAll();
        }
    }//GEN-LAST:event_tb4ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieSelect().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList<String> j1;
    private javax.swing.JList<String> j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JOptionPane jop;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l7;
    private javax.swing.JToggleButton tb1;
    private javax.swing.JToggleButton tb2;
    private javax.swing.JToggleButton tb3;
    private javax.swing.JToggleButton tb4;
    // End of variables declaration//GEN-END:variables

}
