/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tbs;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author patel
 */
public class Opening extends javax.swing.JFrame {

    /**
     * Creates new form Opening
     */
    int a=0;
    public Opening() {
        initComponents();
        Timer timer =new Timer();
        TimerTask task = new TimerTask()
                {
                    public void run()
                {
                  a++;  
                  p1.setValue(a);
                }
                };
        timer.scheduleAtFixedRate(task,0,30);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        p1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(400, 100));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tbs/B_D-round-green-fghdot.png"))); // NOI18N
        jLabel1.setOpaque(true);

        p1.setBackground(new java.awt.Color(51, 51, 255));
        p1.setForeground(new java.awt.Color(0, 0, 255));
        p1.setName(""); // NOI18N
        p1.setStringPainted(true);
        p1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                p1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_p1StateChanged
     if(p1.getValue()==100)
       {
           new Login().setVisible(true);
           dispose();
       }
     
    }//GEN-LAST:event_p1StateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/?useSSL=false", "root", "1234");
            Statement stmt = con.createStatement();
            String q="CREATE DATABASE IF NOT EXISTS tbs;";
            stmt.execute(q);
            String q2="use tbs;";stmt.execute(q2);
            String qua1="create table if not exists temp(seats varchar(3))";
               stmt.execute(qua1);
            
            String q1="CREATE table IF NOT EXISTS user(username varchar(20) NOT NULL,\n" +
"  password varchar(14) DEFAULT NULL,\n" +
"  name varchar(30) DEFAULT NULL,\n" +
"  gender char(1) DEFAULT NULL,\n" +
"  dob date DEFAULT NULL,\n" +
"  mob char(10) DEFAULT NULL,\n" +
"  email varchar(50) DEFAULT NULL,\n" +
"  owner char(1) DEFAULT NULL,\n" +
"  PRIMARY KEY (username)\n" +
") ;";
             stmt.execute(q1);
             
            String q3="create table if not exists movietable (\n" +
"  movie varchar(50) DEFAULT NULL,\n" +
"  date date DEFAULT NULL,\n" +
"  time char(4) DEFAULT NULL,\n" +
"  url varchar(100) DEFAULT NULL\n," +
"tbname char(5));";
              stmt.execute(q3);
             
             
             }
       catch(Exception e)
       {
           System.out.print(e);
       }
    }//GEN-LAST:event_formWindowActivated
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar p1;
    // End of variables declaration//GEN-END:variables
}
